
// This file has been generated by the GUI designer. Do not modify.
namespace PNMail
{
	public partial class LecDlg
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.TextView tvMsg;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button btnDepack;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PNMail.LecDlg
			this.Name = "PNMail.LecDlg";
			this.Title = global::Mono.Unix.Catalog.GetString ("PNMail : Lecture d'un message.");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child PNMail.LecDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.tvMsg = new global::Gtk.TextView ();
			this.tvMsg.CanFocus = true;
			this.tvMsg.Name = "tvMsg";
			this.scrolledwindow1.Add (this.tvMsg);
			w1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1 [this.scrolledwindow1]));
			w3.Position = 0;
			// Internal child PNMail.LecDlg.ActionArea
			global::Gtk.HButtonBox w4 = this.ActionArea;
			w4.Name = "dialog1_ActionArea";
			w4.Spacing = 10;
			w4.BorderWidth = ((uint)(5));
			w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-go-back";
			this.AddActionWidget (this.buttonCancel, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.buttonCancel]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.btnDepack = new global::Gtk.Button ();
			this.btnDepack.CanFocus = true;
			this.btnDepack.Name = "btnDepack";
			this.btnDepack.UseUnderline = true;
			this.btnDepack.Label = global::Mono.Unix.Catalog.GetString ("De packette");
			global::Gtk.Image w6 = new global::Gtk.Image ();
			w6.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cut", global::Gtk.IconSize.Menu);
			this.btnDepack.Image = w6;
			this.AddActionWidget (this.btnDepack, -3);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4 [this.btnDepack]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
			this.btnDepack.Clicked += new global::System.EventHandler (this.OnBtnDepackClicked);
		}
	}
}
