
// This file has been generated by the GUI designer. Do not modify.
namespace PNMail
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action quitAction;
		
		private global::Gtk.Action PreferencesAction;
		
		private global::Gtk.Action PNMailAction;
		
		private global::Gtk.Action PreferencesAction1;
		
		private global::Gtk.Action QuitterAction;
		
		private global::Gtk.Action InformationAction;
		
		private global::Gtk.Action PreferencesAction2;
		
		private global::Gtk.Action selectColorAction;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar menubar2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HButtonBox hbuttonbox4;
		
		private global::Gtk.Button btnMail;
		
		private global::Gtk.Button btnPos;
		
		private global::Gtk.Button btnGrib;
		
		private global::Gtk.Button btnCata;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView nvOut;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.NodeView nvIn;
		
		private global::Gtk.Statusbar statusbar2;
		
		private global::Gtk.Label labGPS;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PNMail.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Quitter");
			this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quitter"), null, "gtk-quit");
			this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Quitter");
			w1.Add (this.quitAction, null);
			this.PreferencesAction = new global::Gtk.Action ("PreferencesAction", global::Mono.Unix.Catalog.GetString ("Preferences"), null, null);
			this.PreferencesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.PreferencesAction, null);
			this.PNMailAction = new global::Gtk.Action ("PNMailAction", global::Mono.Unix.Catalog.GetString ("PNMail"), null, null);
			this.PNMailAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("PNMail");
			w1.Add (this.PNMailAction, null);
			this.PreferencesAction1 = new global::Gtk.Action ("PreferencesAction1", global::Mono.Unix.Catalog.GetString ("Preferences"), null, null);
			this.PreferencesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.PreferencesAction1, null);
			this.QuitterAction = new global::Gtk.Action ("QuitterAction", global::Mono.Unix.Catalog.GetString ("Quitter"), null, null);
			this.QuitterAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
			w1.Add (this.QuitterAction, null);
			this.InformationAction = new global::Gtk.Action ("InformationAction", global::Mono.Unix.Catalog.GetString ("Information"), null, null);
			this.InformationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Information");
			w1.Add (this.InformationAction, null);
			this.PreferencesAction2 = new global::Gtk.Action ("PreferencesAction2", global::Mono.Unix.Catalog.GetString ("Preferences"), null, null);
			this.PreferencesAction2.ShortLabel = global::Mono.Unix.Catalog.GetString ("Preferences");
			w1.Add (this.PreferencesAction2, null);
			this.UIManager.InsertActionGroup (w1, 0);
			global::Gtk.ActionGroup w2 = new global::Gtk.ActionGroup ("Preferences");
			this.selectColorAction = new global::Gtk.Action ("selectColorAction", global::Mono.Unix.Catalog.GetString ("_Preferences"), null, "gtk-select-color");
			this.selectColorAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("_Preferences");
			w2.Add (this.selectColorAction, null);
			this.UIManager.InsertActionGroup (w2, 1);
			global::Gtk.ActionGroup w3 = new global::Gtk.ActionGroup ("Default");
			this.UIManager.InsertActionGroup (w3, 2);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "PNMail.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("PNMail");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("PNMail.Eagles-10.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child PNMail.MainWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='PNMailAction' action='PNMailAction'><menuitem name='QuitterAction' action='QuitterAction'/><menuitem name='InformationAction' action='InformationAction'/></menu><menu name='PreferencesAction1' action='PreferencesAction1'><menuitem name='PreferencesAction2' action='PreferencesAction2'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox2.Add (this.menubar2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString (" O\n u\n t\n B\n o\n x\n");
			this.hbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label1]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbuttonbox4 = new global::Gtk.HButtonBox ();
			this.hbuttonbox4.Name = "hbuttonbox4";
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.btnMail = new global::Gtk.Button ();
			this.btnMail.CanFocus = true;
			this.btnMail.Name = "btnMail";
			this.btnMail.UseUnderline = true;
			this.btnMail.Label = global::Mono.Unix.Catalog.GetString ("Mail");
			this.hbuttonbox4.Add (this.btnMail);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.btnMail]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.btnPos = new global::Gtk.Button ();
			this.btnPos.CanFocus = true;
			this.btnPos.Name = "btnPos";
			this.btnPos.UseUnderline = true;
			this.btnPos.Label = global::Mono.Unix.Catalog.GetString ("Report de position");
			this.hbuttonbox4.Add (this.btnPos);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.btnPos]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.btnGrib = new global::Gtk.Button ();
			this.btnGrib.CanFocus = true;
			this.btnGrib.Name = "btnGrib";
			this.btnGrib.UseUnderline = true;
			this.btnGrib.Label = global::Mono.Unix.Catalog.GetString ("Fichier GRIB");
			this.hbuttonbox4.Add (this.btnGrib);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.btnGrib]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.btnCata = new global::Gtk.Button ();
			this.btnCata.CanFocus = true;
			this.btnCata.Name = "btnCata";
			this.btnCata.UseUnderline = true;
			this.btnCata.Label = global::Mono.Unix.Catalog.GetString ("Catalogue");
			this.hbuttonbox4.Add (this.btnCata);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox4 [this.btnCata]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox3.Add (this.hbuttonbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbuttonbox4]));
			w10.Position = 0;
			w10.Expand = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nvOut = new global::Gtk.NodeView ();
			this.nvOut.CanFocus = true;
			this.nvOut.Name = "nvOut";
			this.GtkScrolledWindow.Add (this.nvOut);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w12.Position = 1;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w13.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w14.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString (" I\n n\n B\n o\n x\n");
			this.hbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label2]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.nvIn = new global::Gtk.NodeView ();
			this.nvIn.CanFocus = true;
			this.nvIn.Events = ((global::Gdk.EventMask)(1024));
			this.nvIn.Name = "nvIn";
			this.GtkScrolledWindow1.Add (this.nvIn);
			this.hbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.GtkScrolledWindow1]));
			w17.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w18.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.statusbar2 = new global::Gtk.Statusbar ();
			this.statusbar2.Name = "statusbar2";
			this.statusbar2.Spacing = 6;
			// Container child statusbar2.Gtk.Box+BoxChild
			this.labGPS = new global::Gtk.Label ();
			this.labGPS.Name = "labGPS";
			this.labGPS.LabelProp = global::Mono.Unix.Catalog.GetString ("Pas de GPS");
			this.statusbar2.Add (this.labGPS);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.statusbar2 [this.labGPS]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox2.Add (this.statusbar2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar2]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 458;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.QuitterAction.Activated += new global::System.EventHandler (this.OnQuitterActionActivated);
			this.InformationAction.Activated += new global::System.EventHandler (this.OnInformationActionActivated);
			this.PreferencesAction2.Activated += new global::System.EventHandler (this.OnPreferencesAction2Activated);
			this.btnMail.Clicked += new global::System.EventHandler (this.OnBtnMailClicked);
			this.btnPos.Clicked += new global::System.EventHandler (this.OnBtnPosClicked);
			this.btnGrib.Clicked += new global::System.EventHandler (this.OnBtnGribClicked);
			this.btnCata.Clicked += new global::System.EventHandler (this.OnBtnCataClicked);
			this.nvOut.RowActivated += new global::Gtk.RowActivatedHandler (this.OnNvOutRowActivated);
			this.nvOut.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnNvOutKeyPressEvent);
			this.nvIn.RowActivated += new global::Gtk.RowActivatedHandler (this.OnNvInRowActivated);
			this.nvIn.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnNvInKeyPressEvent);
		}
	}
}
