
// This file has been generated by the GUI designer. Do not modify.
namespace PNMail
{
	public partial class GribDlg
	{
		private global::Gtk.Notebook nbMain;
		
		private global::Gtk.Table table2;
		
		private global::Gtk.CheckButton cbCAPE;
		
		private global::Gtk.ComboBox cbDPas;
		
		private global::Gtk.CheckButton cbExpo;
		
		private global::Gtk.ComboBox cbGPas;
		
		private global::Gtk.CheckButton cbRain;
		
		private global::Gtk.CheckButton cbVague;
		
		private global::Gtk.Entry eDure;
		
		private global::Gtk.Entry eReqEst;
		
		private global::Gtk.Entry eReqNord;
		
		private global::Gtk.Entry eReqOuest;
		
		private global::Gtk.Entry eReqSud;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Entry eLat;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Entry eLong;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Entry eDure1;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.ComboBox cbDPas1;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.CheckButton cbCape1;
		
		private global::Gtk.CheckButton cbLFTX;
		
		private global::Gtk.CheckButton cbPress;
		
		private global::Gtk.CheckButton cbRain1;
		
		private global::Gtk.CheckButton cbSurfTmp;
		
		private global::Gtk.CheckButton cbWaves;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget PNMail.GribDlg
			this.Name = "PNMail.GribDlg";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child PNMail.GribDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.nbMain = new global::Gtk.Notebook ();
			this.nbMain.CanFocus = true;
			this.nbMain.Name = "nbMain";
			this.nbMain.CurrentPage = 1;
			// Container child nbMain.Gtk.Notebook+NotebookChild
			this.table2 = new global::Gtk.Table (((uint)(7)), ((uint)(3)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.cbCAPE = new global::Gtk.CheckButton ();
			this.cbCAPE.CanFocus = true;
			this.cbCAPE.Name = "cbCAPE";
			this.cbCAPE.Label = global::Mono.Unix.Catalog.GetString ("CAPE");
			this.cbCAPE.DrawIndicator = true;
			this.cbCAPE.UseUnderline = true;
			this.table2.Add (this.cbCAPE);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbCAPE]));
			w2.TopAttach = ((uint)(6));
			w2.BottomAttach = ((uint)(7));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbDPas = global::Gtk.ComboBox.NewText ();
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("12"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("18"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("24"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("36"));
			this.cbDPas.AppendText (global::Mono.Unix.Catalog.GetString ("48"));
			this.cbDPas.AppendText ("");
			this.cbDPas.Name = "cbDPas";
			this.cbDPas.Active = 0;
			this.table2.Add (this.cbDPas);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbDPas]));
			w3.TopAttach = ((uint)(4));
			w3.BottomAttach = ((uint)(5));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbExpo = new global::Gtk.CheckButton ();
			this.cbExpo.CanFocus = true;
			this.cbExpo.Name = "cbExpo";
			this.cbExpo.Label = global::Mono.Unix.Catalog.GetString ("exponnentiel");
			this.cbExpo.DrawIndicator = true;
			this.cbExpo.UseUnderline = true;
			this.table2.Add (this.cbExpo);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbExpo]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(2));
			w4.RightAttach = ((uint)(3));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbGPas = global::Gtk.ComboBox.NewText ();
			this.cbGPas.AppendText (global::Mono.Unix.Catalog.GetString ("0.25"));
			this.cbGPas.AppendText (global::Mono.Unix.Catalog.GetString ("0.5"));
			this.cbGPas.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.cbGPas.AppendText (global::Mono.Unix.Catalog.GetString ("1.5"));
			this.cbGPas.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.cbGPas.AppendText (global::Mono.Unix.Catalog.GetString ("2.5"));
			this.cbGPas.AppendText ("");
			this.cbGPas.Name = "cbGPas";
			this.cbGPas.Active = 0;
			this.table2.Add (this.cbGPas);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbGPas]));
			w5.TopAttach = ((uint)(3));
			w5.BottomAttach = ((uint)(4));
			w5.LeftAttach = ((uint)(2));
			w5.RightAttach = ((uint)(3));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbRain = new global::Gtk.CheckButton ();
			this.cbRain.CanFocus = true;
			this.cbRain.Name = "cbRain";
			this.cbRain.Label = global::Mono.Unix.Catalog.GetString ("Precipitations");
			this.cbRain.DrawIndicator = true;
			this.cbRain.UseUnderline = true;
			this.table2.Add (this.cbRain);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbRain]));
			w6.TopAttach = ((uint)(6));
			w6.BottomAttach = ((uint)(7));
			w6.LeftAttach = ((uint)(2));
			w6.RightAttach = ((uint)(3));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.cbVague = new global::Gtk.CheckButton ();
			this.cbVague.CanFocus = true;
			this.cbVague.Name = "cbVague";
			this.cbVague.Label = global::Mono.Unix.Catalog.GetString ("Houle/Vague");
			this.cbVague.DrawIndicator = true;
			this.cbVague.UseUnderline = true;
			this.table2.Add (this.cbVague);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table2 [this.cbVague]));
			w7.TopAttach = ((uint)(6));
			w7.BottomAttach = ((uint)(7));
			w7.LeftAttach = ((uint)(1));
			w7.RightAttach = ((uint)(2));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.eDure = new global::Gtk.Entry ();
			this.eDure.CanFocus = true;
			this.eDure.Name = "eDure";
			this.eDure.Text = global::Mono.Unix.Catalog.GetString ("48");
			this.eDure.IsEditable = true;
			this.eDure.MaxLength = 3;
			this.eDure.InvisibleChar = '•';
			this.table2.Add (this.eDure);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table2 [this.eDure]));
			w8.TopAttach = ((uint)(5));
			w8.BottomAttach = ((uint)(6));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.XOptions = ((global::Gtk.AttachOptions)(4));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.eReqEst = new global::Gtk.Entry ();
			this.eReqEst.CanFocus = true;
			this.eReqEst.Name = "eReqEst";
			this.eReqEst.Text = global::Mono.Unix.Catalog.GetString ("59W");
			this.eReqEst.IsEditable = true;
			this.eReqEst.MaxLength = 4;
			this.eReqEst.InvisibleChar = '•';
			this.table2.Add (this.eReqEst);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table2 [this.eReqEst]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(2));
			w9.RightAttach = ((uint)(3));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.eReqNord = new global::Gtk.Entry ();
			this.eReqNord.CanFocus = true;
			this.eReqNord.Name = "eReqNord";
			this.eReqNord.Text = global::Mono.Unix.Catalog.GetString ("16N");
			this.eReqNord.IsEditable = true;
			this.eReqNord.MaxLength = 3;
			this.eReqNord.InvisibleChar = '•';
			this.table2.Add (this.eReqNord);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table2 [this.eReqNord]));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.eReqOuest = new global::Gtk.Entry ();
			this.eReqOuest.CanFocus = true;
			this.eReqOuest.Name = "eReqOuest";
			this.eReqOuest.Text = global::Mono.Unix.Catalog.GetString ("61W");
			this.eReqOuest.IsEditable = true;
			this.eReqOuest.MaxLength = 4;
			this.eReqOuest.InvisibleChar = '•';
			this.table2.Add (this.eReqOuest);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.eReqOuest]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.eReqSud = new global::Gtk.Entry ();
			this.eReqSud.CanFocus = true;
			this.eReqSud.Name = "eReqSud";
			this.eReqSud.Text = global::Mono.Unix.Catalog.GetString ("12N");
			this.eReqSud.IsEditable = true;
			this.eReqSud.MaxLength = 3;
			this.eReqSud.InvisibleChar = '•';
			this.table2.Add (this.eReqSud);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table2 [this.eReqSud]));
			w12.TopAttach = ((uint)(2));
			w12.BottomAttach = ((uint)(3));
			w12.LeftAttach = ((uint)(1));
			w12.RightAttach = ((uint)(2));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Durée [heure] : ");
			this.table2.Add (this.label1);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table2 [this.label1]));
			w13.TopAttach = ((uint)(5));
			w13.BottomAttach = ((uint)(6));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.table2.Add (this.label10);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.table2.Add (this.label11);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table2 [this.label11]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Pas [degres] :");
			this.table2.Add (this.label12);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.label12]));
			w16.TopAttach = ((uint)(3));
			w16.BottomAttach = ((uint)(4));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Pas [heure] : ");
			this.table2.Add (this.label13);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.label13]));
			w17.TopAttach = ((uint)(4));
			w17.BottomAttach = ((uint)(5));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w18.LeftAttach = ((uint)(2));
			w18.RightAttach = ((uint)(3));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.LeftAttach = ((uint)(2));
			w19.RightAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.table2.Add (this.label9);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(1));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			this.nbMain.Add (this.table2);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Grib");
			this.nbMain.SetTabLabel (this.table2, this.label2);
			this.label2.ShowAll ();
			// Container child nbMain.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Latitude : ");
			this.hbox1.Add (this.label4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label4]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eLat = new global::Gtk.Entry ();
			this.eLat.TooltipMarkup = "XX.XN";
			this.eLat.CanFocus = true;
			this.eLat.Name = "eLat";
			this.eLat.IsEditable = true;
			this.eLat.InvisibleChar = '•';
			this.hbox1.Add (this.eLat);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.eLat]));
			w23.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Longitude : ");
			this.hbox1.Add (this.label6);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label6]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.eLong = new global::Gtk.Entry ();
			this.eLong.TooltipMarkup = "XXX.XW";
			this.eLong.CanFocus = true;
			this.eLong.Name = "eLong";
			this.eLong.IsEditable = true;
			this.eLong.InvisibleChar = '•';
			this.hbox1.Add (this.eLong);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.eLong]));
			w25.Position = 3;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Durée [j] : ");
			this.hbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label5]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.eDure1 = new global::Gtk.Entry ();
			this.eDure1.CanFocus = true;
			this.eDure1.Name = "eDure1";
			this.eDure1.Text = global::Mono.Unix.Catalog.GetString ("5");
			this.eDure1.IsEditable = true;
			this.eDure1.MaxLength = 3;
			this.eDure1.InvisibleChar = '•';
			this.hbox2.Add (this.eDure1);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.eDure1]));
			w28.Position = 1;
			w28.Expand = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Pas : ");
			this.hbox2.Add (this.label14);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label14]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.cbDPas1 = global::Gtk.ComboBox.NewText ();
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("12"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("18"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("24"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("36"));
			this.cbDPas1.AppendText (global::Mono.Unix.Catalog.GetString ("48"));
			this.cbDPas1.AppendText ("");
			this.cbDPas1.Name = "cbDPas1";
			this.cbDPas1.Active = 0;
			this.hbox2.Add (this.cbDPas1);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.cbDPas1]));
			w30.Position = 3;
			w30.Expand = false;
			w30.Fill = false;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.cbCape1 = new global::Gtk.CheckButton ();
			this.cbCape1.CanFocus = true;
			this.cbCape1.Name = "cbCape1";
			this.cbCape1.Label = global::Mono.Unix.Catalog.GetString ("CAPE");
			this.cbCape1.DrawIndicator = true;
			this.cbCape1.UseUnderline = true;
			this.table1.Add (this.cbCape1);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbCape1]));
			w32.TopAttach = ((uint)(1));
			w32.BottomAttach = ((uint)(2));
			w32.LeftAttach = ((uint)(1));
			w32.RightAttach = ((uint)(2));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbLFTX = new global::Gtk.CheckButton ();
			this.cbLFTX.CanFocus = true;
			this.cbLFTX.Name = "cbLFTX";
			this.cbLFTX.Label = global::Mono.Unix.Catalog.GetString ("LFTX");
			this.cbLFTX.DrawIndicator = true;
			this.cbLFTX.UseUnderline = true;
			this.table1.Add (this.cbLFTX);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbLFTX]));
			w33.TopAttach = ((uint)(1));
			w33.BottomAttach = ((uint)(2));
			w33.LeftAttach = ((uint)(2));
			w33.RightAttach = ((uint)(3));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbPress = new global::Gtk.CheckButton ();
			this.cbPress.CanFocus = true;
			this.cbPress.Name = "cbPress";
			this.cbPress.Label = global::Mono.Unix.Catalog.GetString ("Pression");
			this.cbPress.DrawIndicator = true;
			this.cbPress.UseUnderline = true;
			this.table1.Add (this.cbPress);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbPress]));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbRain1 = new global::Gtk.CheckButton ();
			this.cbRain1.CanFocus = true;
			this.cbRain1.Name = "cbRain1";
			this.cbRain1.Label = global::Mono.Unix.Catalog.GetString ("Precipitations");
			this.cbRain1.DrawIndicator = true;
			this.cbRain1.UseUnderline = true;
			this.table1.Add (this.cbRain1);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbRain1]));
			w35.LeftAttach = ((uint)(2));
			w35.RightAttach = ((uint)(3));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbSurfTmp = new global::Gtk.CheckButton ();
			this.cbSurfTmp.CanFocus = true;
			this.cbSurfTmp.Name = "cbSurfTmp";
			this.cbSurfTmp.Label = global::Mono.Unix.Catalog.GetString ("Temperature surface");
			this.cbSurfTmp.DrawIndicator = true;
			this.cbSurfTmp.UseUnderline = true;
			this.table1.Add (this.cbSurfTmp);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbSurfTmp]));
			w36.TopAttach = ((uint)(1));
			w36.BottomAttach = ((uint)(2));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.cbWaves = new global::Gtk.CheckButton ();
			this.cbWaves.CanFocus = true;
			this.cbWaves.Name = "cbWaves";
			this.cbWaves.Label = global::Mono.Unix.Catalog.GetString ("Houle/Vagues");
			this.cbWaves.DrawIndicator = true;
			this.cbWaves.UseUnderline = true;
			this.table1.Add (this.cbWaves);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.cbWaves]));
			w37.LeftAttach = ((uint)(1));
			w37.RightAttach = ((uint)(2));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table1]));
			w38.Position = 2;
			this.nbMain.Add (this.vbox2);
			global::Gtk.Notebook.NotebookChild w39 = ((global::Gtk.Notebook.NotebookChild)(this.nbMain [this.vbox2]));
			w39.Position = 1;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Spot");
			this.nbMain.SetTabLabel (this.vbox2, this.label3);
			this.label3.ShowAll ();
			w1.Add (this.nbMain);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(w1 [this.nbMain]));
			w40.Position = 0;
			// Internal child PNMail.GribDlg.ActionArea
			global::Gtk.HButtonBox w41 = this.ActionArea;
			w41.Name = "dialog1_ActionArea";
			w41.Spacing = 10;
			w41.BorderWidth = ((uint)(5));
			w41.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w41 [this.buttonCancel]));
			w42.Expand = false;
			w42.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w41 [this.buttonOk]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 585;
			this.DefaultHeight = 315;
			this.Show ();
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
